version: '3'

services:
  downloadarr:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Downloads:/app/Downloads
      - ./Incomplete_Downloads:/app/Incomplete_Downloads
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped